name: CI

on: [push, pull_request]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend deps
        run: |
          pip install -r backend/requirements.txt
      - name: Run backend lint (flake8 optional) and tests
        run: |
          echo "No tests configured yet"
